### INTRODUKTION (15 min, 17:00 - 17:15)

### ALT DET BASALE (30 min, 17:15 - 17:45)

##### Python Scripts / IPython Notebooks

In [1]:
# COMMENTS COMMENTS COMMENTS...

# ALWAYS NICE TO WRITE COMMENTS

In [2]:
print('''
A picture of a dog...
 0____
  ||||
''')


A picture of a dog...
 0____
  ||||



##### Assignment / lister

In [3]:
a = 42

b = [1, 2, 3, 4 , 5, 5]

c = range(3)

d = 'PROSA'

e = ['Peter', 'Rosa', 'Oscar', 'Sebastian', 'Adam']

f = ['D', 4, 'M', e]

In [4]:
print(a)
print(c)
print(d)
print(f)

42
range(0, 3)
PROSA
['D', 4, 'M', ['Peter', 'Rosa', 'Oscar', 'Sebastian', 'Adam']]


In [5]:
for idx in c:
    print(e[idx])

Peter
Rosa
Oscar


In [6]:
f[1] = 40

In [7]:
print(f)

['D', 40, 'M', ['Peter', 'Rosa', 'Oscar', 'Sebastian', 'Adam']]


##### Udvælge elementer i lister. Indeks og slice.

In [8]:
print(b[1])

print(b[-2])

print(b[2:4])

print(b[-3:-1])

print(f[3][2:4])

2
5
[3, 4]
[4, 5]
['Oscar', 'Sebastian']


##### List comprehension

In [9]:
x = [number**2 for number in range(21)]

In [10]:
print(x)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [11]:
y = [number for number in x if number % 2 == 0]

In [12]:
print(y)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [13]:
first_letters = [word[0] for word in e]

In [14]:
print(first_letters)

['P', 'R', 'O', 'S', 'A']


##### Dictionaries

In [15]:
dic = {
    'integer': 42,
    'float': 23.23,
    'string': 'Python rules!',
    'list': ['nested', 'list'],
    'dictionary': {'inception': 'dictionary'}
}

In [16]:
print(dic)

{'integer': 42, 'float': 23.23, 'string': 'Python rules!', 'list': ['nested', 'list'], 'dictionary': {'inception': 'dictionary'}}


In [17]:
print(dic['float'])
print(dic['dictionary'])

23.23
{'inception': 'dictionary'}


In [18]:
dic['float'] = 12.34

In [19]:
for key in dic.keys():
    print(dic[key])

42
12.34
Python rules!
['nested', 'list']
{'inception': 'dictionary'}


In [20]:
for val in dic.values():
    print(val)

42
12.34
Python rules!
['nested', 'list']
{'inception': 'dictionary'}


##### Sets

In [21]:
names1 = set(['John', 'Jane', 'Jack', 'Janice'])

print(names1)

{'Jack', 'John', 'Janice', 'Jane'}


In [22]:
names1.add('Tobias')

print(names1)

{'Jack', 'Tobias', 'John', 'Janice', 'Jane'}


In [23]:
names1.add('Tobias')

print(names1)

{'Jack', 'Tobias', 'John', 'Janice', 'Jane'}


In [24]:
names2 = set(['Anders', 'Line', 'Martin', 'Amalie', 'John', 'Jane'])

In [25]:
print(names1.union(names2))

print(names1.intersection(names2))

{'Jack', 'Anders', 'Line', 'Tobias', 'Martin', 'Amalie', 'John', 'Janice', 'Jane'}
{'John', 'Jane'}


##### Funktioner

In [26]:
print(len(y))
print(sum(y))
print(max(y))

11
1540
400


In [27]:
z = 12.3456789

print(round(z, 2))

12.35


In [28]:
for i in range(10):
    if i > 5:
        break

In [29]:
list(names1)

['Jack', 'Tobias', 'John', 'Janice', 'Jane']

##### Funktioner vi selv laver

In [30]:
def broken_calculator_addition(x, y):
    return x+y+2

def print_result(x, y):
    res = broken_calculator_addition(x, y)
    s = 'When you add %d and %d, you get %d' % (x, y, res)
    print(s)

In [31]:
print_result(25, 15)

When you add 25 and 15, you get 42


##### Classes

In [32]:
class Person:
    
    def __init__(self, first_name, last_name, age):
        self.first_name = first_name
        self.last_name = last_name
        self.age = age
        self.skills = []
        self.workplace = None
    
    def add_skill(self, skill):
        self.skills.append(skill)
        
    def set_workplace(self, workplace):
        self.workplace = workplace

In [33]:
person1 = Person(first_name='Monty', last_name='Python', age=24)

print(person1.first_name)
print(person1.workplace)

Monty
None


In [34]:
person1.set_workplace('Prosa')
person1.add_skill('Knitting')

print(person1.workplace)

Prosa


In [35]:
person2 = Person(first_name='Jens', last_name='Jensen', age=49)
person3 = Person(first_name='Henning', last_name='Havørn', age=35)

persons = [person1, person2, person3]

for person in persons:
    person.add_skill('Python programming')

In [36]:
print(person1.skills)
print(person2.skills)
print(person3.skills)

['Knitting', 'Python programming']
['Python programming']
['Python programming']


##### Bruge pakker fra Python community / Imports

In [37]:
import datetime

print(datetime.date.today())

2018-10-29


In [38]:
import datetime as dt

print(dt.date.today())

2018-10-29


In [39]:
from datetime import date

print(date.today())

2018-10-29


In [40]:
import hello

hello.hello_world()

Hello, PROSA!


In [41]:
from termcolor import cprint 
from pyfiglet import figlet_format

the_dog = '''the dog...
      0____       
         | | | |       '''
cprint(figlet_format(the_dog, font='starwars'), 'green', 'on_grey', attrs=['bold'])

.___________. __    __   _______     _______   ______     _______           
|           ||  |  |  | |   ____|   |       \ /  __  \   /  _____|          
`---|  |----`|  |__|  | |  |__      |  .--.  |  |  |  | |  |  __            
    |  |     |   __   | |   __|     |  |  |  |  |  |  | |  | |_ |           
    |  |     |  |  |  | |  |____    |  '--'  |  `--'  | |  |__| |  __ __ __ 
    |__|     |__|  |__| |_______|   |_______/ \______/   \______| (__|__|__)
                                                                            
                    ___                                                     
                   / _ \                                                    
                  | | | |                                                   
                  | | | |                                                   
                  | |_| |                                                   
                   \___/   ______ ______ ______ ______                      

In [42]:
from __future__ import braces

SyntaxError: not a chance (<ipython-input-42-6d5c5b2f0daf>, line 1)

##### Dataframes med Pandas

In [43]:
import pandas as pd

temp = {'Name': ['Monty Python', 'Jens Jensen', 'Henning Havørn'], 'Age': [24, 49, 35]}

df1 = pd.DataFrame(data=temp)

df1

Name  Age
0    Monty Python   24
1     Jens Jensen   49
2  Henning Havørn   35

In [44]:
df1['Name']

0      Monty Python
1       Jens Jensen
2    Henning Havørn
Name: Name, dtype: object

In [45]:
df1.iloc[0:2]

Name  Age
0  Monty Python   24
1   Jens Jensen   49

In [46]:
df1[df1['Age'] > 30]

Name  Age
1     Jens Jensen   49
2  Henning Havørn   35

In [47]:
df1['Age (squared)'] = df1['Age']**2

df1

Name  Age  Age (squared)
0    Monty Python   24            576
1     Jens Jensen   49           2401
2  Henning Havørn   35           1225

In [48]:
temp = {'Name': ['Monty Python', 'Jens Jensen', 'Henning Havørn', 'Martin Højland'],
        'Is funny': [True, False, True, False]}

df2 = pd.DataFrame(data=temp)

df2

Name  Is funny
0    Monty Python      True
1     Jens Jensen     False
2  Henning Havørn      True
3  Martin Højland     False

In [49]:
df3 = pd.merge(df1, df2, on='Name', how='right')

df3

Name   Age  Age (squared)  Is funny
0    Monty Python  24.0          576.0      True
1     Jens Jensen  49.0         2401.0     False
2  Henning Havørn  35.0         1225.0      True
3  Martin Højland   NaN            NaN     False

In [50]:
df3[df3['Is funny'] == True]

Name   Age  Age (squared)  Is funny
0    Monty Python  24.0          576.0      True
2  Henning Havørn  35.0         1225.0      True

##### Vektorer og matricer med Numpy

In [51]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [52]:
print(x + y + z)

print(x * 10)

print(x**2)

print(x * y)

[12 15 18]
[10 20 30]
[1 4 9]
[ 4 10 18]


In [53]:
X = np.array([x, y, z])

print(X)

print(X.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [54]:
mu = 10
sigma = 2
sample = np.random.normal(loc=mu, scale=sigma, size=5)

In [55]:
print(sample)
print(np.sort(sample))

[13.03868796 13.17329281  9.33730033 12.20098575  9.2993682 ]
[ 9.2993682   9.33730033 12.20098575 13.03868796 13.17329281]


In [56]:
print(np.argwhere(sample > mu))

[[0]
 [1]
 [3]]


### ØVELSER: ALT DET BASALE (15 min, 17:45 - 18:00)

### PAUSE (30 min, 18:00 - 18:30)

### DATA INDSAMLING (15 min, 18:30 - 18:45)

##### Indlæsning af data (txt, csv, Stata, SAS, SPSS, osv.)

In [141]:
df_demo = pd.read_csv('Data/df_demography.csv', sep=',', dtype={'cpr': str})
df_code = pd.read_csv('Data/df_coding_skills.csv', sep=',', dtype={'cpr': str})
df_pers = pd.read_csv('Data/df_personal_characteristic.csv', sep=',', dtype={'cpr': str})

In [142]:
df_code.to_pickle('Data/df_coding_skills.pkl')

In [143]:
df_code = pd.read_pickle('Data/df_coding_skills.pkl')

##### Databaser

##### API'er

##### Scrape data fra hjemmesider

In [144]:
import urllib
from bs4 import BeautifulSoup

url = 'https://www.prosa.dk/arrangementer/'
response = urllib.request.urlopen(url)

soup = BeautifulSoup(response, 'html.parser')

In [145]:
events = []

for link in soup.find_all('span'):
    if link.text:
        events.append(link.text)

In [146]:
for event in events:
    print(event)

Functional Copenhageners Meetup Group
PiO - Prosa i Odense inviterer til workshop: Introduktion til SQL
Aarhus: Introduktion til React
Odense: Workshop i mental træning og mindfulness
Wordpress for øvede 1
Åben workshop for sociale iværksættere (EKSTERN)
Kom godt i gang med Python
Kooperativ erfagruppe
Byg en selvkørende Arduino-robot
Odense: Prototyping og wireframing
Analytics-kursus – Få forretningskritisk indsigt, der kan øge dit forretningspotentiale
Aarhus: Workshop om it-sikkerhed og lockpicking
Eksternt: AI, dataetik og den personlige informationsøkonomi
Aarhus: Vinsmagning
Photoshop for øvede
Tillidsrepræsentantens rolle i forhold til persondata
Aarhus: Sådan træner du din Arduino
Webinar: Microsoft Azure overblik og status
Aarhus: Formøde til delegeretforsamlingen
Coldfront Community Day
Kooperativ erfagruppe
Wordpress for øvede 2
Forretningshemmeligheder - hvad betyder det for dig
Odense: Kursus i præsentationsteknik
Aflyst: GDPR/DPO-erfagruppe
Byg en selvkørende Arduino-rob

### DATA ANALYSE (45 MIN, 18:45-19:30)

##### Merge data frames

In [196]:
df = pd.merge(df_demo, df_code, on='cpr')
df = pd.merge(df, df_pers, on='cpr')

In [197]:
df.iloc[:10]

cpr municipality  salary  kan_R  kan_python  height  weight  \
0  1203913055      Esbjerg  377218  False       False    1.80    82.1   
1  1308952064   Sønderborg  286903   True        True    1.58    61.6   
2  2410936634      Thisted  337835   True       False    1.66    73.7   
3  1605952976    København  273928  False        True    1.71    74.2   
4  2802942759    Silkeborg  318220   True       False    1.91    83.8   
5  2007903527     Syddjurs  325773  False        True    1.75    84.7   
6  2406877802      Horsens  327235  False       False    1.92    61.9   
7  1002624535       Dragør  689159  False        True    1.74    88.8   
8  0312717659     Hvidovre  544341  False       False    1.67    88.6   
9  1508663376      Herning  554418  False        True    1.75    72.1   

   hair_len  
0       7.5  
1      47.2  
2      28.4  
3      46.8  
4       6.3  
5       2.0  
6      26.0  
7       5.1  
8       4.4  
9      32.6

##### Feature engineering

In [198]:
df['gender'] = df['cpr'].str[9].apply(int)
df['gender'] = np.where(df['gender'] % 2 == 0, 'woman', 'man')

In [199]:
df['year'] = df['cpr'].str[4:6]
df['year'] = '19' + df['year']
#df['year'] = df['year'].apply(int)

In [200]:
df['month'] = df['cpr'].str[2:4]
#df['month'] = df['month'].apply(int)

In [201]:
df['day'] = df['cpr'].str[0:2]
#df['day'] = df['day'].apply(int)

In [202]:
df['birthday'] = pd.to_datetime(df['day'] + df['month'] + df['year'], format='%d%m%Y')

In [209]:
now = pd.Timestamp(dt.datetime.now())
df['age'] = (now - df['birthday'])
df['age'] = df['age'].astype('<m8[Y]')

In [210]:
df.iloc[:10]

cpr municipality  salary  kan_R  kan_python  height  weight  \
0  1203913055      Esbjerg  377218  False       False    1.80    82.1   
1  1308952064   Sønderborg  286903   True        True    1.58    61.6   
2  2410936634      Thisted  337835   True       False    1.66    73.7   
3  1605952976    København  273928  False        True    1.71    74.2   
4  2802942759    Silkeborg  318220   True       False    1.91    83.8   
5  2007903527     Syddjurs  325773  False        True    1.75    84.7   
6  2406877802      Horsens  327235  False       False    1.92    61.9   
7  1002624535       Dragør  689159  False        True    1.74    88.8   
8  0312717659     Hvidovre  544341  False       False    1.67    88.6   
9  1508663376      Herning  554418  False        True    1.75    72.1   

   hair_len gender  year month day   birthday   age  
0       7.5    man  1991    03  12 1991-03-12  27.0  
1      47.2  woman  1995    08  13 1995-08-13  23.0  
2      28.4  woman  1993    10  24 1993-10-24  25.0  
3      46.8  woman  1995    05  16 1995-05-16  23.0  
4       6.3    man  1994    02  28 1994-02-28  24.0  
5       2.0    man  1990    07  20 1990-07-20  28.0  
6      26.0  woman  1987    06  24 1987-06-24  31.0  
7       5.1    man  1962    02  10 1962-02-10  56.0  
8       4.4    man  1971    12  03 1971-12-03  46.0  
9      32.6  woman  1966    08  15 1966-08-15  52.0

##### Lineær regression

In [213]:
x = df['height'].values
y = df['weight'].values

In [217]:
from scipy import stats

slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)

##### Supervised learning (Logistisk regression med Scikit-learn)

In [261]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [255]:
X = df[['height', 'weight']].values
y = df['gender'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [259]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

print(log_reg.coef_)
print(log_reg.intercept_)

[[-0.94824917 -0.32712224]]
[27.04830077]


In [267]:
y_pred = log_reg.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(sum(y_test == y_pred) / len(y_test))

[[759  32]
 [ 37 726]]
0.9555984555984556
0.9555984555984556


##### Unsupervised learning (Kmeans med Scikit-learn)

In [269]:
from sklearn.cluster import KMeans

In [297]:
kmeans = KMeans(n_clusters=2)
kmeans.fit(X_train)

print(kmeans.cluster_centers_[0])
print(kmeans.cluster_centers_[1])

[ 1.68546122 69.23236515]
[ 1.80987338 86.59652597]


In [305]:
df_cluster = pd.DataFrame()
df_cluster['height'] = X_train[:, 0]
df_cluster['weight'] = X_train[:, 1]
df_cluster['cluster'] = kmeans.labels_

print(df_cluster[df_cluster['cluster'] == 0].mean())

print(df_cluster[df_cluster['cluster'] == 1].mean())

height      1.685461
weight     69.232365
cluster     0.000000
dtype: float64
height      1.809873
weight     86.596526
cluster     1.000000
dtype: float64


In [293]:
cluster_pred = kmeans.predict(X_test)
print(cluster_pred)

cluster_labels = y_test == 'woman' #man/woman
print(cluster_labels)

print(accuracy_score(cluster_labels, cluster_pred))

[0 1 1 ... 0 0 1]
[False  True  True ...  True False  True]
0.9485199485199485


### DATA VISUALISERING (15 min, 19:30 - 19:45)

##### Visualisering med Matplotlib

##### Scatter plot

##### Bar plot

### TWITTER DATA (15 MIN, 19:45-20:00)

### ØVELSE (45 min, 20:00 - 20:45)

### SPØRGSMÅL / BUFFERTID (15 min, 20:45 - 21:00)